import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Provider from "./provider";
import ScrollToTop from "@/components/ui/ScrollToTop";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "AI Recruiter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={inter.className}>

        <Provider>
          {children}
          <ScrollToTop />
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
